-- INSERTING INITIAL DATA
use vooo_prod_backend;
SET FOREIGN_KEY_CHECKS = 0;
-- aggregator
INSERT INTO `aggregator` (`id`,`id_client`,`name`) VALUES (11,1076,'Destaxa');
-- client
INSERT INTO `client` (`id`,`economic_group_id`,`id_address`,`id_contact`,`id_document`,`id_author`,`headquarter_id`,`id_aggregator`,`name`,`trading`,`brand`,`status`,`created_at`,`updated_at`) VALUES (1076,NULL,NULL,NULL,1076,1,NULL,11,'Nexu','Nexu Tecnologia Em Capturas E Processamento De Transacoes Ltda','Nexu',1,'2020-08-18 20:20:05','2020-08-20 08:59:50');
INSERT INTO `client` (`id`,`economic_group_id`,`id_address`,`id_contact`,`id_document`,`id_author`,`headquarter_id`,`id_aggregator`,`name`,`trading`,`brand`,`status`,`created_at`,`updated_at`) VALUES (1507,NULL,NULL,NULL,1507,3579,NULL,1,'EPLP Tecnologia de Pagamentos LTDA','EPLP Tecnologia de Pagamentos LTDA','EPAG',1,'2021-10-14 12:05:35','2021-10-25 18:37:21');
INSERT INTO `client` (`id`,`economic_group_id`,`id_address`,`id_contact`,`id_document`,`id_author`,`headquarter_id`,`id_aggregator`,`name`,`trading`,`brand`,`status`,`created_at`,`updated_at`) VALUES (2210,NULL,NULL,NULL,2207,3579,NULL,1,'Tradio Pagamentos Ltda','Tradio Pagamentos Ltda','Tradio Bank',1,'2023-11-09 17:31:55','2023-11-13 13:13:48');
#user
INSERT INTO `user` (`id`,`id_client`,`id_role`,`id_contact`,`headquarter_id`,`id_aggregator`,`username`,`email`,`password`,`status`,`created_at`,`updated_at`,`last_access_date`,`last_password_change_date`) VALUES (1,NULL,1,NULL,NULL,1,'Vooo','vooo@vooo.com.br','$2b$13$7XiJFkFH11aVeTUHnYRCZ.pmpzKjrwJIFrqE2uXneRPr5bTIJk442',1,'2016-10-07 23:28:02','2023-05-29 10:54:03','2024-08-23 17:17:24','2083-08-28');
INSERT INTO `user_control` (`id`,`client_id`,`user_id`,`time_window_in_minutes`,`password_days_to_expire`,`description`) VALUES (0,NULL,NULL,30,90,'Tempo padrão, caso não tenha customização');
SET FOREIGN_KEY_CHECKS = 1;

-- INSERTING MIGRATION OBJECTS
use vooo_migration;
-- schmas
insert into schma (name, ref_type) value ('vooo_prod_backend', 'external');
insert into schma (name, ref_type) value ('vooo_prod_rawdata', 'internal');

-- expts
insert into expts (stat) value ("table_name like 'shellbox%'");
insert into expts (stat) value ("table_name like 'tmp_%'");
insert into expts (stat) value ("table_name like 'temp_%'");
insert into expts (stat) value ("table_name like 'analise%'");
insert into expts (stat) value ("table_name = 'mercadopago_transacao31.03'");
insert into expts (stat) value ("table_name = 'mercadopago_transacao31.03'");
insert into expts (stat) value ("table_name = 'connect_item_btg'");
insert into expts (stat) value ("table_name = 'group_bkp'");
insert into expts (stat) value ("table_name = 'rel_ant'");
insert into expts (stat) value ("table_name = 'sales_statement'");
insert into expts (stat) value ("table_name = 'stix_1405'");
insert into expts (stat) value ("table_name = 'transacao_btg'");
insert into expts (stat) value ("table_name = 'transacoes_erradas'");
insert into expts (stat) value ("table_name = 'transacoes_sap_08_07'");

-- refs
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client', 'id_aggregator', 'vooo_prod_backend', 'aggregator', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'address', 'id', 'vooo_prod_backend', 'client', 'id_address');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'billing', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'cielo_auth', 'id_client', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'cielo_auth_log', 'id_client', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'cielo_auth_merchants', 'id_client', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_average_sales', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_bank_balance', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_edi_extra_path', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_extra_contract', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_status_detail', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_status_log', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_crawler', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_edi', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_edi_tivit', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_pagador', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_rest', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_sales_system', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_sitef_provider', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_connector_status', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_customization', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_dashboard', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_external_id', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_notprocessing_alert', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_processing_notification', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_provider_composition', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_service', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'client_user', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection_crawler', 'connection_id', 'vooo_prod_backend', 'connection', 'connection_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection_edi', 'connection_id', 'vooo_prod_backend', 'connection', 'connection_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection_error', 'connection_id', 'vooo_prod_backend', 'connection', 'connection_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection_item', 'connection_id', 'vooo_prod_backend', 'connection', 'connection_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connect_item_btg', 'item_id', 'vooo_prod_backend', 'connection_item', 'item_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection_rest', 'connection_id', 'vooo_prod_backend', 'connection', 'connection_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection_sales_lot', 'connection_id', 'vooo_prod_backend', 'connection', 'connection_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'connection_sales_system', 'connection_id', 'vooo_prod_backend', 'connection', 'connection_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'daily_reports_rates', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'daily_reports_receipts', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'daily_reports_sales', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'document', 'id', 'vooo_prod_backend', 'client', 'id_document');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'files_aws_s3_client', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'files_aws_s3_control', 'client_folder_id', 'vooo_prod_backend', 'files_aws_s3_client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'files_control_action', 'file_name', 'vooo_prod_backend', 'connection_edi', 'file');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'files_control_vector', 'id', 'vooo_prod_backend', 'files_control_action', 'files_control_vector_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'files_control_vector_ftp', 'id', 'vooo_prod_backend', 'files_control_action', 'files_control_vector_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'generic_layout', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'generic_layout_connect_fields', 'layout_id', 'vooo_prod_backend', 'generic_layout', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'generic_layout_map_values', 'field_id', 'vooo_prod_backend', 'generic_layout_connect_fields', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'generic_layout_upload', 'layout_id', 'vooo_prod_backend', 'generic_layout', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'monthly_reports_rates', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'monthly_reports_receipts', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_agenda', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_agenda_reversal', 'output_agenda_id', 'vooo_prod_backend', 'output_agenda', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_agenda_sales', 'output_agenda_id', 'vooo_prod_backend', 'output_agenda', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_agenda_settlement', 'output_agenda_id', 'vooo_prod_backend', 'output_agenda', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_agenda_settlement_reference', 'output_agenda_id', 'vooo_prod_backend', 'output_agenda', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_alert', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_anticipation', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_composition', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_composition_item', 'output_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_connection_item', 'output_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_connection_item_back', 'output_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_item', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_item_composition_reference', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_manual_conciliation', 'id', 'vooo_prod_backend', 'output_sales', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_outstanding', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_reconciliation', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_reconciliation_alert', 'output_reconciliation_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_reference', 'output_reconciliation_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_report_files', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_reversal', 'output_reconciliation_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_reversal_adjusts', 'id', 'vooo_prod_backend', 'output_reversal_id', 'output_reversal_adjusts_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_reversal_bin', 'output_reconciliation_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_sales', 'output_reconciliation_id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_sales_adjusts', 'id', 'vooo_prod_backend', 'output_sales', 'output_sales_adjusts_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_sales_bin', 'output_sales_id', 'vooo_prod_backend', 'output_sales', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_sales_fee', 'output_sales_id', 'vooo_prod_backend', 'output_sales', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_sales_performance', 'id', 'vooo_prod_backend', 'output_sales', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_sales_settlement_item', 'output_sales_id', 'vooo_prod_backend', 'output_sales', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_settlement', 'id', 'vooo_prod_backend', 'output_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_settlement_bank', 'id', 'vooo_prod_backend', 'output_setlement', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_settlement_files', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_settlement_item', 'output_settlement_id', 'vooo_prod_backend', 'output_settlement', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_statement', 'id', 'vooo_prod_backend', 'ouput_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'output_unschedule', 'id', 'vooo_prod_backend', 'ouput_item', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'pagarme_payable_control', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'pagarme_transaction_control', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'r_admin_fee', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'r_client_exchange_fee', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'r_client_interchange_fee', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'reconciliation_client_provider_actions', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'reconciliation_client_provider_default_account', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'reconciliation_client_rule', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'reconciliation_fee_config', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'reconciliation_transaction_fee', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'rede_request', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'sales', 'item_id', 'vooo_prod_backend', 'connection_item', 'item_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'sales_closed_period', 'item_id', 'vooo_prod_backend', 'connection_item', 'item_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'sales_complement', 'item_id', 'vooo_prod_backend', 'sales', 'item_id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'sitef_control', 'client_id', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'user', 'id_client', 'vooo_prod_backend', 'client', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'user_backoffice', 'id_user', 'vooo_prod_backend', 'user', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'user_control', 'user_id', 'vooo_prod_backend', 'user', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'user_login_control', 'user_id', 'vooo_prod_backend', 'user', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'user_notification_processing', 'user_id', 'vooo_prod_backend', 'user', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'user_old_passwords', 'user_id', 'vooo_prod_backend', 'user', 'id');
insert into ref_init (referrer_schema, referrer_table, referrer_field, referenced_schema, referenced_table, referenced_field) value ('vooo_prod_backend', 'user_status_log', 'user_id', 'vooo_prod_backend', 'user', 'id');


commit;